version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  eureka-server:
    image: eurika
    build:
      context: ./eurika
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network
  web-api:
    image: web-api
    build:
      context: ./web-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
  beer-service:
    image: beer
    build:
      context: ./beer-service
      dockerfile: Dockerfile
    ports:
      - "8081"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
    deploy:
      replicas: 3
  rabbit-service:
    image: rabbit
    build:
      context: ./rabbit-service
      dockerfile: Dockerfile
    ports:
      - "8082"
    networks:
      - microservices-network
    depends_on:
      - eureka-server
  stew-service:
    image: stew
    build:
      context: ./stew-service
      dockerfile: Dockerfile
    ports:
      - "8083"
    networks:
      - microservices-network
    depends_on:
      - eureka-server

networks:
  microservices-network:
    driver: bridge